# Generated by Django 4.2 on 2025-09-08 14:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="имя"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="фамилия"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата рождения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Актер",
                "verbose_name_plural": "Актеры",
                "db_table": "actors",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="код"
                    ),
                ),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
                "db_table": "countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="имя"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="фамилия"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата рождения"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, verbose_name="биография"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="movies.country",
                        verbose_name="страна",
                    ),
                ),
            ],
            options={
                "verbose_name": "Режиссер",
                "verbose_name_plural": "Режиссеры",
                "db_table": "directors",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="описание"),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "db_table": "genres",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="название"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="описание"),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1888),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="год выпуска",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Длительность в минутах",
                        null=True,
                        verbose_name="длительность (мин)",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        verbose_name="ссылка на изображение",
                    ),
                ),
                (
                    "imdb_rating",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                        verbose_name="рейтинг IMDb",
                    ),
                ),
                (
                    "kinopoisk_rating",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                        verbose_name="рейтинг Кинопоиска",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="дата обновления"
                    ),
                ),
                (
                    "actors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="movies",
                        to="movies.actor",
                        verbose_name="актеры",
                    ),
                ),
                (
                    "countries",
                    models.ManyToManyField(
                        blank=True,
                        related_name="movies",
                        to="movies.country",
                        verbose_name="страны",
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="movies.director",
                        verbose_name="режиссер",
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True,
                        related_name="movies",
                        to="movies.genre",
                        verbose_name="жанры",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фильм",
                "verbose_name_plural": "Фильмы",
                "db_table": "movies",
                "ordering": ["-year", "title"],
            },
        ),
        migrations.AddField(
            model_name="actor",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="movies.country",
                verbose_name="страна",
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["year"], name="movies_year_1feb9b_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["title"], name="movies_title_179e04_idx"
            ),
        ),
    ]
