# Generated by Django 4.2 on 2025-09-08 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "movies",
            "0002_rating_userpreferences_remove_actor_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Жанр", "verbose_name_plural": "Жанры"},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name": "Фильм", "verbose_name_plural": "Фильмы"},
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={
                "verbose_name": "Рейтинг",
                "verbose_name_plural": "Рейтинги",
            },
        ),
        migrations.AlterModelOptions(
            name="userpreferences",
            options={
                "verbose_name": "Предпочтение пользователя",
                "verbose_name_plural": "Предпочтения пользователей",
            },
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Название жанра"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Режиссер"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                to="movies.genre", verbose_name="Жанры"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image_url",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="URL изображения"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(
                max_length=200, verbose_name="Название фильма"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(verbose_name="Год выпуска"),
        ),
        migrations.AlterField(
            model_name="rating",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.movie",
                verbose_name="Фильм",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                verbose_name="Оценка",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="disliked_movies",
            field=models.ManyToManyField(
                blank=True,
                related_name="disliked_by",
                to="movies.movie",
                verbose_name="Не понравившиеся фильмы",
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="favorite_genres",
            field=models.ManyToManyField(
                blank=True, to="movies.genre", verbose_name="Любимые жанры"
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="liked_movies",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_by",
                to="movies.movie",
                verbose_name="Понравившиеся фильмы",
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
