# Generated by Django 4.2 on 2025-09-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_review"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
