# Generated by Django 4.2 on 2025-09-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="password"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Имя пользователя",
                        max_length=30,
                        verbose_name="имя",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Фамилия пользователя",
                        max_length=30,
                        verbose_name="фамилия",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Номер пользователя",
                        max_length=20,
                        unique=True,
                        verbose_name="номер",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Сотрудник проекта",
                        verbose_name="Сотрудник ли",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Администратор проекта",
                        verbose_name="Админ ли",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "db_table": "users",
                "ordering": ["phone"],
            },
        ),
    ]
